version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: examen_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.eltfire
    environment:
      DATABASE_URL: postgresql+psycopg://user:password@db:5432/examen_db
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: inflation-data
    depends_on:
      - db
      - minio
    ports:
      - "8000:8000"

volumes:
  db_data:
  minio_data: