"""Initial migration

Revision ID: 2807e77cf736
Revises: 
Create Date: 2025-07-07 17:14:39.208847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2807e77cf736'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=150), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('inflation', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gdp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=150), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('inflation', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gdp')
    op.drop_table('consumer')
    # ### end Alembic commands ###
